[package]
name = "slowpty"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
exec = "0.3"
libc = "0.2"
log = "0.4"
mio = "0.6"
